# Generated by Django 6.0.2 on 2026-02-24 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('lecture_hall', 'Lecture Hall'), ('computer_lab', 'Computer Lab'), ('physics_lab', 'Physics Lab'), ('chemistry_lab', 'Chemistry Lab'), ('biology_lab', 'Biology Lab')], max_length=20),
        ),
    ]
