# Generated by Django 6.0.2 on 2026-03-01 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_profile_must_change_password_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='scheduler.programme'),
        ),
        migrations.AddField(
            model_name='profile',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='year_of_study',
            field=models.CharField(blank=True, choices=[('Year 1', 'Year 1'), ('Year 2', 'Year 2'), ('Year 3', 'Year 3'), ('Year 4', 'Year 4')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
