# Generated by Django 6.0.2 on 2026-03-06 11:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_profile_programme_profile_registration_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='session_group_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
