# Generated by Django 6.0.2 on 2026-03-24 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_timetableentry_session_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='is_practical',
            field=models.BooleanField(default=False, help_text='Check if this unit requires a laboratory session instead of a lecture hall'),
        ),
        migrations.AddField(
            model_name='unit',
            name='preferred_lab_type',
            field=models.CharField(blank=True, choices=[('computer_lab', 'Computer Lab'), ('physics_lab', 'Physics Lab'), ('chemistry_lab', 'Chemistry Lab'), ('biology_lab', 'Biology Lab'), ('any_lab', 'Any Lab (no preference)')], help_text='Specify the required lab type. Leave blank for theory units.', max_length=20, null=True),
        ),
    ]
