# Generated by Django 6.0.2 on 2026-03-24 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_unit_is_practical_preferred_lab_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='attributes',
            field=models.CharField(blank=True, help_text='Comma-separated tags, e.g. "Projector, AC, Power Outlets"', max_length=255),
        ),
    ]
