# Generated by Django 6.0.2 on 2026-03-25 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_room_attributes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='is_practical',
        ),
        migrations.AddField(
            model_name='programme',
            name='domain_category',
            field=models.CharField(blank=True, choices=[('ict', 'ICT / Computing'), ('biology', 'Biology / Life Sciences'), ('chemistry', 'Chemistry'), ('physics', 'Physics / Electronics / Engineering'), ('general', 'General / Multi-discipline')], help_text='Controls which lab types units in this programme may use. ICT = Computer Labs (+ Physics Lab for electronics); Biology = Biology Labs; Chemistry = Chemistry Labs; Physics = Physics Labs; General = any lab.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='lab_hours_per_week',
            field=models.PositiveIntegerField(blank=True, help_text='For Hybrid units: how many hours per week are spent in a lab. The remaining hours go to a lecture hall. Leave blank for Theory/Practical units.', null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='session_type',
            field=models.CharField(choices=[('theory', 'Theory Only — all sessions in lecture hall'), ('practical', 'Practical Only — all sessions in lab'), ('hybrid', 'Hybrid — split between lecture hall and lab')], default='theory', help_text='Theory: only lecture halls. Practical: only labs. Hybrid: some sessions in hall, some in lab.', max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Structured room attributes for smart classification. e.g. {"has_projector": true, "air_conditioned": true, "software": ["MATLAB", "AutoCAD"], "max_voltage": 240}'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='preferred_lab_type',
            field=models.CharField(blank=True, choices=[('computer_lab', 'Computer Lab'), ('physics_lab', 'Physics Lab'), ('chemistry_lab', 'Chemistry Lab'), ('biology_lab', 'Biology Lab'), ('any_lab', 'Any Lab (programme default)')], help_text='For Practical and Hybrid units. Leave as "Any Lab" to let the programme domain decide, or choose a specific lab type to override.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='required_hours',
            field=models.PositiveIntegerField(default=3, help_text='Total contact hours per week for this unit'),
        ),
    ]
